# sso (204):
pocket_id_encryption_key: "{{ vault_pocket_id_encryption_key }}"

# Bastion (201)
tls_mode: "mkcert"      # mkcert | letsencrypt
tls_cert_path: "/etc/nginx/tls/{{ gateway_domain_root }}.crt"
tls_key_path:  "/etc/nginx/tls/{{ gateway_domain_root }}.key"

nord_country: "united_states"
nord_city: "buffalo"
dns_base: /opt/dns
unbound_listen_ip: "127.0.0.1"
unbound_port: 5335
unbound_rrset_cache: "256m"
unbound_msg_cache: "128m"
unbound_root_hints: "{{ dns_base | default('/opt/dns') }}/unbound/root.hints"
tz: "America/New_York"