pg_version: "16"
pg_db_dir: "/opt/postgres/data"
pg_backups_dir: "/opt/postgres/backups"
pg_listen_addr: "0.0.0.0"
pg_db_authentik: "authentik"
pg_user_authentik: "authentik"
pg_password_authentik: "{{ vault_pg_password_authentik }}"
pg_allowed_cidrs:
  - "192.168.1.204/32"   # SSO
  - "192.168.1.205/32"   # Webapps


# sso (204):
authentik_domain: "sso.fakult.net"   # also defined in external
authentik_secret_key: "{{ vault_authentik_secret_key }}"
authentik_bootstrap_email: "jfakult15@gmail.com"
authentik_bootstrap_password: "{{ vault_authentik_bootstrap_pw }}"

# external DB (on 203)
pg_host: "192.168.1.203"
pg_port: "5432"
pg_db: "authentik"
pg_user: "authentik"
pg_password: "{{ vault_pg_password_authentik }}"

# Bastion (201)
tls_mode: "mkcert"      # mkcert | letsencrypt
tls_cert_path: "/etc/nginx/tls/{{ gateway_domain_root }}.crt"
tls_key_path:  "/etc/nginx/tls/{{ gateway_domain_root }}.key"

sso_base_url: "https://{{ authentik_domain }}"
forward_auth_path: "/outpost.goauthentik.io/auth/nginx"

nord_country: "united_states"
nord_city: "buffalo"
dns_base: /opt/dns
unbound_listen_ip: "127.0.0.1"
unbound_port: 5335
unbound_rrset_cache: "256m"
unbound_msg_cache: "128m"
unbound_root_hints: "{{ dns_base | default('/opt/dns') }}/unbound/root.hints"
tz: "America/New_York"