- name: Create dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/nginx
    - /etc/nginx/conf.d
    - /etc/nginx/tls
    - /var/log/nginx
    - /opt/gateway
    - /srv/files

- name: Drop nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"

- name: Drop compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/gateway/docker-compose.yml
    mode: "0644"

- name: Bring up gateway stack
  shell: docker compose up -d
  args: { chdir: /opt/gateway }

- name: Validate nginx syntax (post-start)
  shell: docker exec rp-nginx nginx -t
  register: ngchk
  failed_when: ngchk.rc != 0
  changed_when: false