- name: Create dirs
  file:
    path: "/opt/authentik/app"
    state: directory
    mode: "0750"

- name: Drop compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/authentik/docker-compose.yml
    mode: "0644"

- name: Up Authentik
  shell: docker compose up -d
  args: { chdir: /opt/authentik }

- name: Wait for Authentik HTTP
  uri:
    url: "http://127.0.0.1"
    status_code: 200
  register: _ak
  retries: 40
  delay: 3
  until: _ak.status == 200
