gateway_domain_root: "fakult.net"

ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo

sso_fqdn: "sso.fakult.net"   # also defined in infra
pki_build_dir: "./pki-out"

ak_compose_dir: "/opt/authentik"
ak_discovery_dir: "{{ ak_compose_dir }}/certs/{{ sso_fqdn }}"

nas_ip: "192.168.1.199"

media_mount_opts:   "rw,hard,nconnect=8,vers=4.2,noatime,rsize=1048576,wsize=1048576,x-systemd.automount,_netdev,nofail"
webapps_mount_opts: "rw,hard,nconnect=8,vers=4.2,noatime,rsize=1048576,wsize=1048576,x-systemd.automount,_netdev,nofail"
bastion_mount_opts: "ro,hard,nconnect=8,vers=4.2,noatime,rsize=1048576,wsize=1048576,x-systemd.automount,_netdev,nofail"


pihole_api_token: "VAULT_PIHOLE_TOKEN"

monitoring_net: "monitoring"
monitoring_dir: "/opt/monitoring"
exporters_net: "exporters"
prometheus_scrape_interval: "30s"
exporters_dir: "/opt/exporters"


# Prometheus jobs (targets are host:port; exporters expose on 9113, 9100, 9101-like default ports below)
prometheus_targets:
  node:        ["192.168.1.200:9100", "192.168.1.206:9100", "192.168.1.202:9100", "192.168.1.211:9100"]
  nginx:       ["192.168.1.200:9113"]
  jellyfin:    ["192.168.1.206:9594"]
  pihole:      ["192.168.1.202:9617"]
  cadvisor:    ["192.168.1.200:8080", "192.168.1.206:8080", "192.168.1.202:8080"]
  blackbox_http:
    - { target: "http://192.168.1.200",        module: "http_2xx" }
    - { target: "https://192.168.1.200",       module: "http_2xx" }
    - { target: "http://192.168.1.206:8096",     module: "http_2xx" }
    - { target: "http://192.168.1.202/admin",      module: "http_2xx" }
  blackbox_icmp:
    - { target: "192.168.1.200" }  # Bastion
    - { target: "192.168.1.206" }  # Media Server
    - { target: "192.168.1.202" }  # DNS
    - { target: "192.168.1.211" }  # Monitoring Server