---
- name: Configure base settings
  hosts: all
  become: true
  become_method: sudo
  roles:
    - base
  tags:
    - base
    - tested

- name: Setup local ssl certs
  hosts: localhost
  gather_facts: false
  roles:
    - local_pki
  tags:
    - tested

# Setup critical infrastructure (DB, SSO, Bastion). Order matters
- name: Configure DB
  hosts: db
  become: true
  become_method: sudo
  pre_tasks:
    - import_tasks: roles/misc/tasks/install_docker_and_compose.yml
  roles:
    - db
  tags:
    - tested

- name: Configure SSO
  hosts: sso
  become: true
  become_method: sudo
  pre_tasks:
    - import_tasks: roles/misc/tasks/install_docker_and_compose.yml
  roles:
    - sso
  tags:
    - tested

- name: Configure Bastion
  hosts: bastion
  become: true
  become_method: sudo
  pre_tasks:
    - import_tasks: roles/misc/tasks/install_docker_and_compose.yml
  roles:
    - bastion
  tags:
    - tested

- name: Configure DNS
  hosts: dns
  become: true
  become_method: sudo
  pre_tasks:
    - import_tasks: roles/misc/tasks/install_docker_and_compose.yml
  roles:
    - dns
  tags:
    - tested

- name: Configure Media Server
  hosts: media
  become: true
  become_method: sudo
  pre_tasks:
    - import_tasks: roles/misc/tasks/install_docker_and_compose.yml
  roles:
    - media
  tags: tested

- name: Configure Webapps Server
  hosts: webapps
  become: true
  become_method: sudo
  pre_tasks:
    - import_tasks: roles/misc/tasks/install_docker_and_compose.yml
  roles:
    - webapps